### PR TITLE
New type: SimpleBar

### PR DESCRIPTION
**Pull request by Maschina**

### CODE REVIEW

**Comment by f3dm76** [comment]
Hey @Maschina , thank you for your work, but the build fails with this error
Screenshot 2021-04-22 at 09 48 54
Would you please look into this? Have a great day!

**Comment by Maschina** [comment]
Thanks for the hint, should be fixed now.

**Comment by f3dm76** [comment]
Screenshot 2021-04-23 at 09 09 07
@Maschina New day, new errors - would you kindly address them, and have a nice day!

`❌  /Users/travis/build/exyte/ActivityIndicatorView/Source/Indicators/SimpleBarIndicatorView.swift:43:38: reference to property 'backgroundColor' in closure requires explicit 'self.' to make capture semantics explicit
                    .foregroundColor(backgroundColor)
                                     ^
❌  /Users/travis/build/exyte/ActivityIndicatorView/Source/Indicators/SimpleBarIndicatorView.swift:46:54: reference to property 'max' in closure requires explicit 'self.' to make capture semantics explicit
                    .frame(width: Swift.min(CGFloat((max-min)*value)*geometry.size.width, geometry.size.width), height: geometry.size.height)
                                                     ^
❌  /Users/travis/build/exyte/ActivityIndicatorView/Source/Indicators/SimpleBarIndicatorView.swift:46:58: reference to property 'min' in closure requires explicit 'self.' to make capture semantics explicit
                    .frame(width: Swift.min(CGFloat((max-min)*value)*geometry.size.width, geometry.size.width), height: geometry.size.height)
                                                         ^
❌  /Users/travis/build/exyte/ActivityIndicatorView/Source/Indicators/SimpleBarIndicatorView.swift:46:63: reference to property 'value' in closure requires explicit 'self.' to make capture semantics explicit
                    .frame(width: Swift.min(CGFloat((max-min)*value)*geometry.size.width, geometry.size.width), height: geometry.size.height)
                                                              ^
❌  /Users/travis/build/exyte/ActivityIndicatorView/Source/Indicators/SimpleBarIndicatorView.swift:47:38: reference to property 'barColor' in closure requires explicit 'self.' to make capture semantics explicit
                    .foregroundColor(barColor)
                                     ^
⚠️  /Users/travis/build/exyte/ActivityIndicatorView/Source/Indicators/SimpleBarIndicatorView.swift:38:9: result of 'GeometryReader<Content>' initializer is unused
        GeometryReader { geometry in
        ^              ~~~~~~~~~~~~~
❌  /Users/travis/build/exyte/ActivityIndicatorView/Source/Indicators/SimpleBarIndicatorView.swift:33:25: function declares an opaque return type, but has no return statements in its body from which to infer an underlying type
    var body: some View {
                        ^
`

**Comment by f3dm76** [comment]
Hey @Maschina, would you please fix the errors (BTW I updated minimum ios version, errors might have fixed themselves)? Also, colors of the indicators should be enum params, like with gradient indicator.

**Pull request closed without merging**
